name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: accelerate-devops
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx" --collect:"XPlat Code Coverage"
    - name: Push result to Testspace server
      run: |
        tree
        testspace **/*.trx
        testspace **/*.xml
      if: always()
