name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: accelerate-devops
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx" --collect:"XPlat Code Coverage"
    - name: Push result to Testspace server
      run: |
        tree
        echo "Upload test results..."
        testspace **/*.trx
        echo "Upload code coverage..."
        testspace **/*.xml
      if: always()
    - name: Upload test results to BuildPulse for flaky test detection
      if: '!cancelled()'
      uses: Workshop64/buildpulse-action@v0.7.0
      with:
        account: 62378660
        repository: 435575531
        path: 'FlakyTests/TestResults/*.trx'
        key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
        secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
