name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: accelerate-devops
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=TestResults.xml" --collect:"XPlat Code Coverage"
    
    - name: Delete second coverage file
      run: |
        shopt -s globstar; rm -rf FlakyTests/TestResults/_fv*
        tree FlakyTests/TestResults
        
    - name: Push test results to Testspace
      run: |
        testspace FlakyTests/TestResults/**/*.xml
      if: '!cancelled()'
      
    - name: Upload test results to BuildPulse
      uses: Workshop64/buildpulse-action@v0.7.0
      with:
        account: 62378660
        repository: 435575531
        path: 'FlakyTests/TestResults/TestResults.xml'
        key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
        secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
      if: '!cancelled()'
      
    - name: Publish test results to GitHub
      uses: EnricoMi/publish-unit-test-result-action@v1.25
      with:
        files: FlakyTests/TestResults/TestResults.xml
